# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{real-growl}
  s.version = "0.2.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin DeWind"]
  s.date = %q{2010-01-18}
  s.description = %q{A Growl notification library that uses native c bindings to interact with GrowlApplicationBridge rather than Growl's network API.}
  s.email = %q{dewind@atomicobject.com}
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README.rdoc"
  ]
  s.files = [
    "README.rdoc",
     "Rakefile",
     "ext/real_growl_api.c",
     "ext/real_growl_api.h",
     "ext/ruby_delegate.h",
     "ext/ruby_delegate.m",
     "lib/real_growl.rb"
  ]
  s.homepage = %q{http://github.com/dewind/real-growl}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.5}
  s.summary = %q{Growl notification library that uses native c bindings.}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
    else
    end
  else
  end
end

