# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "real-growl"
  s.version = "0.7.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Justin DeWind"]
  s.date = "2011-12-18"
  s.description = "A Growl notification library that uses native c bindings to interact with GrowlApplicationBridge rather than Growl's network API."
  s.email = "dewind@atomicobject.com"
  s.executables = ["realgrowl"]
  s.extensions = ["ext/extconf.rb"]
  s.extra_rdoc_files = [
    "README.md"
  ]
  s.files = [
    "Rakefile",
    "ext/real_growl_api.c",
    "ext/real_growl_api.h",
    "ext/ruby_delegate.c",
    "ext/ruby_delegate.h",
    "lib/real_growl.rb"
  ]
  s.homepage = "http://github.com/dewind/real-growl"
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Growl notification library that was built using native c bindings."

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<slop>, [">= 0"])
    else
      s.add_dependency(%q<slop>, [">= 0"])
    end
  else
    s.add_dependency(%q<slop>, [">= 0"])
  end
end

